### Напишите программы, которые создают следующие массивы NumPy:


#### 1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы. Затем загрузите его и выведите на экран.

In [4]:
import numpy as np

arr = np.array([1,7,13,105])

print(f"Массив: {arr}")
print(f"Размер памяти: {arr.nbytes}")

np.savetxt("./arr.txt",arr, fmt="%d")

np.save("./arr.npy", arr)

load_txt = np.loadtxt('./arr.txt', dtype=np.int32)
print(f"Загруженный текстовый: {load_txt}")

load_bin = np.load('./arr.npy')
print(f"Загруженный бинарный: {load_bin}")

Массив: [  1   7  13 105]
Размер памяти: 32
Загруженный текстовый: [  1   7  13 105]
Загруженный бинарный: [  1   7  13 105]


#### 2. Три массива: из 10 нулей, 10 единиц, 10 пятерок.


In [5]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10,5)
print(f"Нулевой: {zeros} \nЕдиничный: {ones} \nИз пятерок: {fives}")


Нулевой: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Единичный: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
Из пятерок: [5 5 5 5 5 5 5 5 5 5]


#### 3. Массив последовательности четных целых чисел от 30 до 70


In [6]:
print(f"Последовательность от 30 до 40 четных чисел {np.arange(30,71,2)}") 


Последовательность от 30 до 40 четных чисел [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### 4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.


In [7]:
print(f"10 элементов между 5 и 50: {np.linspace(5,50,10)}")


10 элементов между 5 и 50: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


###     5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.


In [9]:
print(f"Массив 3x3x3 случайных чисел: \n{np.random.randint(1,101, size=(3,3,3))}") 


Массив 3x3x3 случайных чисел: 
[[[ 52  45   7]
  [100  12  99]
  [ 87  76   4]]

 [[ 59  76  38]
  [ 66  22  11]
  [ 14  26  88]]

 [[ 47  35  19]
  [ 51  77  12]
  [ 40  51  70]]]


####     6. Массив 3х4, заполненной значениями от 30 до 41.


In [10]:
print(f"Массив 3x4 от 30 41: \n{np.arange(30,42).reshape(3,4)}")


Массив 3x4 от 30 41: 
[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


####    7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0.


In [11]:
arr_border = np.ones((10,10))
arr_border[1:-1,1:-1] = 0
print(f"Массив 10х10, границы = 1, внутри = 0: \n{arr_border}")


Массив 10х10, границы = 1, внутри = 0: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


####    8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.


In [12]:
arr_diagonal = np.zeros((5,5))
np.fill_diagonal(arr_diagonal,range(1,6))
print(f"Массив 5х5 из нулей с диагональю 1-5: \n{arr_diagonal}")


Массив 5х5 из нулей с диагональю 1-5: 
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


####   9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на главной диагонали.

In [13]:
arr_chess = np.zeros((4,4))
arr_chess[::2,1::2] = 1
arr_chess[1::2,::2] = 1
print(f"Шахматная с нулями на диагонали: \n{arr_chess}")


Шахматная с нулями на диагонали: 
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


####    10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата.


In [14]:
print(f"Март 2017: \n{np.arange("2017-03","2017-04", dtype='datetime64[D]')}")


Март 2017: 
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']
